/* Automatically generated by './build/bin/build-entry.js' */

import Card from './packages/card/index.vue'
import Loading from './packages/loading/index.vue'
import Pagination from './packages/pagination/index.vue'
import Table from './packages/table/index.vue'
import Box from './packages/box/index.vue'
import Button from './packages/button/index.vue'
import Grade from './packages/grade/index.vue'
const components = [Card, Loading, Pagination, Table, Box, Button, Grade]

const install = function (Vue) {
  components.forEach(component => {
    Vue.component(component.name, component)
  })
}

export default install
